-- AlterTable
ALTER TABLE "Machine" ADD COLUMN     "totalJobsCompleted" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "totalJobsFailed" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "trustScore" DOUBLE PRECISION NOT NULL DEFAULT 50.0;
